// dwf - multiplayer Dwarf Fortress in the browser, as a DFHack plugin
// Copyright (C) 2026 Gabriel Rios
// Copyright (C) 2026 Jake Taplin
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, version 3 of the License.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See LICENSE.
//
// SPDX-License-Identifier: AGPL-3.0-only

#include "portrait_sweep.h"

#include "diagnostics.h"
#include "save_barrier.h"
#include "sdl_capture.h"
#include "unit_portrait.h"

#include "modules/DFSDL.h"
#include "df/unit.h"

#include <atomic>
#include <chrono>
#include <deque>
#include <mutex>
#include <sstream>
#include <unordered_map>
#include <unordered_set>

namespace dwf {
namespace {

// PORTRAITS-ROOT (B128), restored 2026-07-20. Portraits are generated by calling DF's OWN
// one-argument lazy portrait generator directly on the render thread (unit_portrait.cpp,
// exe-pinned + SEH-latched). The rejected mechanisms stay rejected: no view-sheet is opened or
// impersonated, no viewscreen logic/render is called, and no SDL target or interface state is
// held across frames. The sweep's job here is only honest bookkeeping and PACING: at most one
// unit is dispatched per DF update tick, with a minimum wall-clock gap, a session `limit N`
// canary cap, and hard gates on save barriers, world changes, and the fault latch.

constexpr auto MIN_DISPATCH_GAP = std::chrono::milliseconds(250);

std::mutex g_mu;
uintptr_t g_world_identity = 0;
bool g_enabled = true;
int g_limit = 0;                      // 0 = unlimited; otherwise max generations this session
std::deque<int32_t> g_queue_fort;     // fort-controlled units first
std::deque<int32_t> g_queue_other;
std::unordered_set<int32_t> g_queued;     // membership for both queues
std::unordered_set<int32_t> g_no_art;     // generator ran; DF has no portrait art for them
std::unordered_set<int32_t> g_done;       // generated or already-present, this world
std::unordered_map<int32_t, std::string> g_failed;
long g_generated = 0;
long g_existing = 0;
long g_attempted = 0;
std::atomic<bool> g_in_flight(false);
std::chrono::steady_clock::time_point g_last_dispatch{};

void classify_locked(int32_t unit_id, NativePortraitOutcome outcome, const std::string& err) {
    switch (outcome) {
    case NativePortraitOutcome::Generated:
        g_done.insert(unit_id);
        ++g_generated;
        break;
    case NativePortraitOutcome::AlreadyExists:
        g_done.insert(unit_id);
        ++g_existing;
        break;
    case NativePortraitOutcome::NoPortraitArt:
        g_no_art.insert(unit_id);
        break;
    case NativePortraitOutcome::Blocked:
        // Transient (save in progress, unit temporarily unresolvable): requeue quietly.
        if (g_queued.insert(unit_id).second)
            g_queue_other.push_back(unit_id);
        break;
    case NativePortraitOutcome::Unavailable:
    case NativePortraitOutcome::Faulted:
        g_failed[unit_id] = err;
        break;
    }
}

} // namespace

void portrait_sweep_observe_world(uintptr_t world_identity) {
    std::lock_guard<std::mutex> lock(g_mu);
    if (world_identity == 0 || world_identity == g_world_identity)
        return;
    g_world_identity = world_identity;
    g_queue_fort.clear();
    g_queue_other.clear();
    g_queued.clear();
    g_no_art.clear();
    g_done.clear();
    g_failed.clear();
}

void portrait_sweep_note_unit(int32_t unit_id, bool fort_priority) {
    if (unit_id < 0)
        return;
    std::lock_guard<std::mutex> lock(g_mu);
    if (g_no_art.count(unit_id) || g_done.count(unit_id) || g_failed.count(unit_id))
        return;
    if (!g_queued.insert(unit_id).second)
        return;
    if (fort_priority)
        g_queue_fort.push_back(unit_id);
    else
        g_queue_other.push_back(unit_id);
}

void portrait_sweep_request_unit(int32_t unit_id) {
    if (unit_id < 0)
        return;
    std::lock_guard<std::mutex> lock(g_mu);
    // An explicit browser request retries even a previously failed/no-art unit once more.
    g_no_art.erase(unit_id);
    g_failed.erase(unit_id);
    if (g_queued.insert(unit_id).second)
        g_queue_fort.push_front(unit_id);
}

void portrait_sweep_tick() {
    // Runs on DF's update thread: NEVER block here, and never touch native UI or renderer
    // state directly. All native work happens inside one short render-thread callback.
    if (save_barrier_active() || unit_portrait_native_generator_faulted())
        return;
    if (g_in_flight.load())
        return;

    int32_t unit_id = -1;
    {
        std::lock_guard<std::mutex> lock(g_mu);
        if (!g_enabled)
            return;
        if (g_limit > 0 && g_attempted >= g_limit)
            return;
        auto now = std::chrono::steady_clock::now();
        if (now - g_last_dispatch < MIN_DISPATCH_GAP)
            return;
        if (!g_queue_fort.empty()) {
            unit_id = g_queue_fort.front();
            g_queue_fort.pop_front();
        } else if (!g_queue_other.empty()) {
            unit_id = g_queue_other.front();
            g_queue_other.pop_front();
        } else {
            return;
        }
        g_queued.erase(unit_id);
        g_last_dispatch = now;
        ++g_attempted;
    }

    g_in_flight.store(true);
    DFHack::runOnRenderThread([unit_id]() {
        // try_lock, not lock: an HTTP thread holds capture_state_mutex while WAITING on its own
        // queued render callback; blocking here would deadlock the render queue behind it.
        std::unique_lock<std::recursive_mutex> capture(capture_state_mutex(), std::try_to_lock);
        NativePortraitOutcome outcome = NativePortraitOutcome::Blocked;
        std::string err;
        if (!capture.owns_lock()) {
            err = "capture state busy";
        } else if (save_barrier_active()) {
            err = "save in progress";
        } else {
            outcome = unit_portrait_generate_native_on_render(df::unit::find(unit_id), &err);
        }
        {
            std::lock_guard<std::mutex> lock(g_mu);
            classify_locked(unit_id, outcome, err);
        }
        g_in_flight.store(false);
    });
}

void portrait_sweep_abort_active() {
    // No native UI or renderer state is ever held across frames; any queued render callback
    // re-checks the save barrier and re-resolves its unit by id before doing anything. Drop the
    // queues so a save or world unload leaves no stale work behind — the stream re-notes any
    // unit that still has portrait_texpos == 0 on its next scan.
    std::lock_guard<std::mutex> lock(g_mu);
    g_queue_fort.clear();
    g_queue_other.clear();
    g_queued.clear();
}

void portrait_sweep_set_enabled(bool enabled) {
    std::lock_guard<std::mutex> lock(g_mu);
    g_enabled = enabled;
}

void portrait_sweep_set_limit(int limit) {
    std::lock_guard<std::mutex> lock(g_mu);
    g_limit = limit < 0 ? 0 : limit;
}

void portrait_sweep_rearm() {
    std::lock_guard<std::mutex> lock(g_mu);
    g_queue_fort.clear();
    g_queue_other.clear();
    g_queued.clear();
    g_no_art.clear();
    g_failed.clear();
    g_done.clear();
    g_attempted = 0;
}

std::string portrait_sweep_status() {
    std::string why;
    const bool available = unit_portrait_native_generator_available(&why);
    const bool faulted = unit_portrait_native_generator_faulted();
    std::lock_guard<std::mutex> lock(g_mu);
    std::ostringstream ss;
    ss << "portrait sweep: generation=";
    if (faulted)
        ss << "FAULT-LATCHED-OFF";
    else if (!available)
        ss << "unavailable (" << why << ")";
    else
        ss << (g_enabled ? "on" : "off");
    ss << " generated=" << g_generated
       << " existing=" << g_existing
       << " no-art=" << g_no_art.size()
       << " failed=" << g_failed.size()
       << " pending=" << (g_queue_fort.size() + g_queue_other.size())
       << " attempted=" << g_attempted
       << " limit=" << (g_limit > 0 ? std::to_string(g_limit) : std::string("none"));
    return ss.str();
}

} // namespace dwf
